import{defineConfig}from'vite';import{readdirSync}from'node:fs';import{resolve,basename}from'node:path';
const input=Object.fromEntries(readdirSync('.').filter(f=>f.endsWith('.html')).map(f=>[basename(f,'.html'),resolve(f)]));
// Prerendered news detail pages live in news/ (generated by scripts/build.mjs before this runs).
try{for(const f of readdirSync('news').filter(f=>f.endsWith('.html')))input[`news/${basename(f,'.html')}`]=resolve('news',f)}catch{}
input.admin=resolve('admin/index.html');
export default defineConfig({build:{rollupOptions:{input}},server:{port:5173}});
