import{writeFile,mkdir}from'node:fs/promises';import{execFileSync}from'node:child_process';
const routes=['index','adopt','foster','volunteer','donate','tnr','about','found-a-cat','happy-tails','news','events','contact','privacy','terms','404'];
const generated={
 'happy-tails':['Happy Tails','Happy adoption stories','Celebrating cats who found their people.'],
 news:['News','News and updates','Follow the latest work from our foster homes and community.'],
 events:['Events','Upcoming events','Meet fellow cat lovers and support our rescue.'],
 privacy:['Privacy policy','Your privacy matters','We collect only the information you choose to send through our forms and use it to respond to you. We do not sell personal information.'],
 terms:['Website terms','Terms of use','This website provides general rescue information. Animal availability and services may change.'],
 '404':['Page not found','That page wandered off','Try the home page or contact us if you need help.']};
const crumb=n=>JSON.stringify({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:'https://grandmascatcoalition.org'},{'@type':'ListItem',position:2,name:n}]});
for(const [slug,[title,heading,copy]]of Object.entries(generated)){const html=`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Grandma's Cat Coalition</title><meta name="description" content="${copy}"><link rel="canonical" href="https://grandmascatcoalition.org/${slug}"><meta property="og:title" content="${title} | Grandma's Cat Coalition"><meta property="og:description" content="${copy}"><meta name="twitter:card" content="summary"><script type="application/ld+json">${crumb(title)}</script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header" data-header></header><main id="main"><section class="hero"><div class="wrap"><h1>${heading}</h1><p>${copy}</p></div></section><section class="section"><div class="wrap"><div class="notice"><p>Fresh content will appear here as our volunteers add it.</p></div></div></section></main><footer class="site-footer" data-footer></footer><script type="module" src="/src/main.js"></script></body></html>`;await writeFile(`${slug}.html`,html)}
await mkdir('public',{recursive:true});await writeFile('public/robots.txt','User-agent: *\nAllow: /\nSitemap: https://grandmascatcoalition.org/sitemap.xml\n');await writeFile('public/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.filter(r=>r!=='404').map(r=>`<url><loc>https://grandmascatcoalition.org/${r==='index'?'':r}</loc></url>`).join('')}</urlset>`);
execFileSync(process.execPath,['node_modules/vite/bin/vite.js','build'],{stdio:'inherit'});
